web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes: 
    - ./code:/code
  environment:
    XDEBUG_CONFIG: remote_host=host.docker.internal
  links:
    - "couchdb:database"
    - mysql
    - maildev

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=oleoleole

maildev:
  image: djfarrelly/maildev
  ports:
   - "8081:80"
  links:
    - couchdb

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=oleoleole
    - PHP_UPLOAD_MAX_FILESIZE=500MB

couchdb:
 image: apache/couchdb:2.2.0
 ports:
    - "5984:5984"
 volumes:
    - "./couch/data:/usr/local/var/lib/couchdb"
    - "./couch/log:/usr/local/var/log/couchdb"

